//! The validation report: `README.md` (renders on GitHub), SVG plots, PNG snapshots and a
//! machine-readable `results.json` (for comparing backends in Phase 2).

use std::fmt::Write as _;
use std::path::Path;

use anyhow::{Context, Result};
use serde::Serialize;

use crate::{fmt_num, CaseResult, Level};

/// How the suite was run.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RunInfo {
    pub level: Level,
    pub backend: String,
    pub collision: String,
    pub threads: usize,
    pub cpu: String,
    pub generator: String,
    pub commit: Option<String>,
    pub seconds: f64,
}

fn status(passed: Option<bool>) -> &'static str {
    match passed {
        Some(true) => "✅ pass",
        Some(false) => "❌ **fail**",
        None => "info",
    }
}

fn cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

/// Writes the report into `dir`, replacing the files of a previous report.
pub fn write(dir: &Path, info: &RunInfo, results: &[CaseResult]) -> Result<()> {
    std::fs::create_dir_all(dir).with_context(|| format!("cannot create {}", dir.display()))?;
    for entry in std::fs::read_dir(dir)?.flatten() {
        let p = entry.path();
        if p.extension().is_some_and(|e| e == "svg" || e == "png") {
            std::fs::remove_file(&p)?;
        }
    }

    let level = match info.level {
        Level::Quick => "quick",
        Level::Full => "full",
    };
    let mut md = String::new();
    let _ = writeln!(md, "# Validation report\n");
    let _ = writeln!(
        md,
        "Generated by `cfd-cli verify --{level}` ({}). Method and cases: \
         [08 — Validation guide](../../docs/08-validation-guide.md); tolerances: \
         [04 §7](../../docs/04-numerical-methods.md#7-validation). Reference data with sources: \
         [`validation/references/`](../references/).\n",
        info.generator
    );
    let passed = results.iter().filter(|r| r.passed()).count();
    let _ = writeln!(
        md,
        "| Level | Backend | Collision | Threads | CPU | Commit | Total time | Result |"
    );
    let _ = writeln!(
        md,
        "|-------|---------|-----------|---------|-----|--------|------------|--------|"
    );
    let _ = writeln!(
        md,
        "| {level} | {} | {} | {} | {} | {} | {:.0} s | {passed}/{} cases pass |\n",
        info.backend,
        info.collision,
        info.threads,
        cell(&info.cpu),
        info.commit.as_deref().unwrap_or("unknown"),
        info.seconds,
        results.len()
    );

    let _ = writeln!(md, "## Summary\n");
    let _ = writeln!(md, "| Case | Result | Checks | Time |");
    let _ = writeln!(md, "|------|--------|--------|------|");
    for r in results {
        let checks: Vec<String> = r
            .metrics
            .iter()
            .filter(|m| m.passed().is_some())
            .map(|m| {
                let mark = if m.passed() == Some(true) {
                    "✅"
                } else {
                    "❌"
                };
                format!("{mark} {} = {}", m.name, fmt_num(m.value))
            })
            .collect();
        let _ = writeln!(
            md,
            "| [{}](#{}) | {} | {} | {:.1} s |",
            r.title,
            r.id,
            status(Some(r.passed())),
            cell(&checks.join("<br>")),
            r.seconds
        );
    }
    md.push('\n');

    for r in results {
        let _ = writeln!(
            md,
            "<a id=\"{}\"></a>\n## {} — {}\n",
            r.id,
            r.title,
            status(Some(r.passed()))
        );
        let _ = writeln!(md, "*Case `{}`. Reference: {}.*\n", r.id, r.reference);
        if !r.description.is_empty() {
            let _ = writeln!(md, "{}\n", r.description);
        }
        if let Some(f) = &r.failure {
            let _ = writeln!(md, "> **The case did not complete:** {}\n", cell(f));
        }
        if !r.metrics.is_empty() {
            let _ = writeln!(
                md,
                "| Quantity | Value | Reference | Error | Limit | Result |"
            );
            let _ = writeln!(
                md,
                "|----------|-------|-----------|-------|-------|--------|"
            );
            for m in &r.metrics {
                let _ = writeln!(
                    md,
                    "| {} | {} | {} | {} | {} | {} |",
                    cell(&m.name),
                    fmt_num(m.value),
                    cell(&m.reference),
                    m.error.map(fmt_num).unwrap_or_default(),
                    m.limit.map(fmt_num).unwrap_or_default(),
                    status(m.passed())
                );
            }
            md.push('\n');
        }
        for t in &r.tables {
            let _ = writeln!(md, "**{}**\n", t.title);
            let _ = writeln!(md, "| {} |", t.headers.join(" | "));
            let _ = writeln!(md, "|{}", "---|".repeat(t.headers.len()));
            for row in &t.rows {
                let _ = writeln!(
                    md,
                    "| {} |",
                    row.iter().map(|c| cell(c)).collect::<Vec<_>>().join(" | ")
                );
            }
            md.push('\n');
        }
        for p in &r.plots {
            std::fs::write(dir.join(&p.file), p.to_svg())?;
            let _ = writeln!(md, "![{}]({})\n", p.title, p.file);
        }
        for s in &r.snapshots {
            std::fs::write(dir.join(&s.file), s.image.encode_png()?)?;
            let _ = writeln!(md, "![{}]({})\n*{}*\n", s.caption, s.file, s.caption);
        }
        if !r.runs.is_empty() {
            let _ = writeln!(md, "<details><summary>Runs</summary>\n");
            let _ = writeln!(
                md,
                "| Run | Fluid cells | Steps | Time | MLUPS | Converged |"
            );
            let _ = writeln!(
                md,
                "|-----|-------------|-------|------|-------|-----------|"
            );
            for s in &r.runs {
                let conv = match s.converged {
                    Some(true) => "yes",
                    Some(false) => "**no**",
                    None => "—",
                };
                let _ = writeln!(
                    md,
                    "| {} | {} | {} | {:.1} s | {:.0} | {conv} |",
                    cell(&s.label),
                    s.fluid_cells,
                    s.steps,
                    s.seconds,
                    s.mlups()
                );
            }
            let _ = writeln!(md, "\n</details>\n");
        }
    }
    std::fs::write(dir.join("README.md"), md)?;

    #[derive(Serialize)]
    struct Json<'a> {
        run: &'a RunInfo,
        cases: &'a [CaseResult],
    }
    std::fs::write(
        dir.join("results.json"),
        serde_json::to_string_pretty(&Json {
            run: info,
            cases: results,
        })? + "\n",
    )?;
    Ok(())
}
